import random
import os
import textwrap
from PIL import Image, ImageDraw, ImageFont
from pyrogram import Client, filters
from pyrogram.types import Message
from userbot.helpers.scripts import edit_or_reply
from userbot.helpers.misc import prefix

@Client.on_message(filters.command("coin", prefix) & filters.me)
async def coin_cmd(client: Client, message: Message):
    """Flip a coin."""
    result = random.choice(["Heads 🪙", "Tails 🦅"])
    await edit_or_reply(message, f"<b>🪙 Coin Flip:</b> {result}")

@Client.on_message(filters.command("dice", prefix) & filters.me)
async def dice_cmd(client: Client, message: Message):
    """Roll a dice."""
    result = random.randint(1, 6)
    await edit_or_reply(message, f"<b>🎲 You rolled a:</b> {result}")

@Client.on_message(filters.command("meme", prefix) & filters.me)
async def meme_cmd(client: Client, message: Message):
    """
    Add text to an image.
    Usage: .meme [top];[bottom] (reply to image)
    """
    msg = await edit_or_reply(message, "<b>🎨 Generating Meme...</b>")
    
    replied = message.reply_to_message
    if not replied or not replied.media:
        await msg.edit("<b>❌ Reply to an image!</b>")
        return

    text = " ".join(message.command[1:])
    if ";" in text:
        top_text, bottom_text = text.split(";", 1)
    else:
        top_text, bottom_text = text, ""

    try:
        # Download image
        photo_path = await client.download_media(replied)
        
        # Process with PIL
        img = Image.open(photo_path)
        draw = ImageDraw.Draw(img)
        
        # Load default font (or fallback)
        # We try to use a system font or default
        try:
            font_path = "arial.ttf" # Windows default
            font = ImageFont.truetype(font_path, size=int(img.width / 10))
        except:
            font = ImageFont.load_default()

        # Helper to draw text with outline
        def draw_text_with_outline(text, position, anchor):
            # Calculate position to center
            # Simple outline simulation
            x, y = position
            fill_color = "white"
            outline_color = "black"
            
            # Draw outline
            for adj in range(-2, 3):
                for ops in range(-2, 3):
                    draw.text((x+adj, y+ops), text, font=font, fill=outline_color, anchor=anchor)
            
            # Draw text
            draw.text((x, y), text, font=font, fill=fill_color, anchor=anchor)

        width, height = img.size
        
        if top_text:
            draw_text_with_outline(top_text.upper(), (width / 2, 10), "mt")
        
        if bottom_text:
            draw_text_with_outline(bottom_text.upper(), (width / 2, height - 10 - int(img.width/10)), "mt")

        # Save
        out_path = f"downloads/meme_{int(time.time())}.jpg"
        img.save(out_path)

        # Upload
        await client.send_photo(
            chat_id=message.chat.id,
            photo=out_path,
            caption=f"<b>😂 Meme Generated by CybroX</b>"
        )
        await msg.delete()
        
    except Exception as e:
        await msg.edit(f"<b>❌ Meme Error:</b> {str(e)}")
    finally:
        # Cleanup
        if 'photo_path' in locals() and os.path.exists(photo_path):
            os.remove(photo_path)
        if 'out_path' in locals() and os.path.exists(out_path):
            os.remove(out_path)
